replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

livenessProbe:
  tcpSocket:
    port: http
readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 20

autoscaling:
  enabled: false
